### ISSUE TITLE
what the log_gaussian loss's mean?

### ISSUE THREAD

**Issue by dongfangduoshou123** [pianomania/infoGAN-pytorch#3]
class log_gaussian:
  def __call__(self, x, mu, var):
    logli = -0.5*(var.mul(2*np.pi)+1e-6).log() - \
            (x-mu).pow(2).div(var.mul(2.0)+1e-6)  
    return logli.sum(1).mean().mul(-1)

 1、What do mu and var represent?
2、I'm doubt about the log_gaussion's theory.

thank you!

**Comment by dongfangduoshou123** [comment]
https://www.jiqizhixin.com/articles/2018-10-29-21
this explantation is good.

**Comment by pianomania** [comment]
Yeah, the explanation is very clear.

Thank you for your sharing!
